### PR TITLE
Poetry cache

### LINKED ISSUE #40: Add dependency caching for faster builds
```yaml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-python@v2
  with:
    python-version: '3.9'
    cache: 'pip'
- run: pip install -r requirements.txt
- run: pip test
```

Question: It should work fine with poetry, right ?

Reference: https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/

### PR DESCRIPTION
**Pull request by sureshdsk**
fixes #40 
- added poetry dependancy cache for github workflow

### CODE REVIEW

**Comment by sureshdsk** [comment]
@guilatrova please take a look at this PR!

**Comment by guilatrova** [comment]
Hi @sureshdsk 
Do you mind reviewing the https://github.com/guilatrova/tryceratops/blob/38bd6cdb95e57bd9674fd5b061abef63ec94c85e/docs/CONTRIBUTING.md#conventional-commits ? The PR needs to follow the conventional commits to generate proper documentatio.

**Comment by sureshdsk** [comment]
@guilatrova rebased and updated commit messages!

**Comment by guilatrova** [comment]
@sureshdsk All commits should be starting with just `ci:` because otherwise, it will generate a new release (even though there's no real feature).

**Comment by sureshdsk** [comment]
@guilatrova updated

**Comment by guilatrova** [comment]
@sureshdsk It's failing :(

**Comment by sureshdsk** [comment]
@guilatrova sorry about that :( 
This is was not there when I raised the PR initially. This error is due to recent change in black(click's latest release broke) as reported here https://github.com/psf/black/issues/2964

Updating black to 22.3.0 as suggested in the issue. 

but another error in mypy is popping up in local, But i haven't changed any python code. but passed from CI run https://github.com/sureshdsk/tryceratops/actions/runs/2182427398 

```
src/tryceratops/__main__.py:26: error: Argument 1 to "Choice" has incompatible type "Set[str]"; expected "Sequence[str]"
```

**Comment by guilatrova** [comment]
@sureshdsk Fixing mypy is on my list... For now I'm merging it as is. Thank you very much for your patience and support on making Tryceratops better! 🥳

**Pull request merged**
